apiVersion: v1
kind: Service
metadata:
  name: scalable-pod-identifier-service
spec:
  selector:
    app: scalable-pod-identifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort